#!/bin/sh

ROOTDEV=/dev/mmcblk0p28

NEED_BALANCE=0
# Threshold for percentage of free space allocation to run balance
BALANCE_THRESHOLD=75

check_balance_need()
{
# Check how near we are for full allocation of free space
	RAWUSE=`btrfs fi show | grep $ROOTDEV | \
			awk -F ' ' '{print $6}'| grep -o '[0-9.]'*`
	echo rawuse $RAWUSE

	MAXUSE=`btrfs fi show | grep $ROOTDEV | \
			awk -F ' ' '{print $4}'| grep -o '[0-9.]*'`
	echo maxuse $MAXUSE

	USED=`awk -v rawuse=$RAWUSE -v maxuse=$MAXUSE 'BEGIN {printf "%d\n", \
			rawuse * 100 / maxuse}'`
	echo used $USED:

	if test $USED -ge $BALANCE_THRESHOLD; then
		NEED_BALANCE=1;
	else
		NEED_BALANCE=0;
	fi
}



keepalive &
PID_KEEPALIVE=$!

echo $PID_KEEPALIVE

check_balance_need

echo $NEED_BALANCE

if test $NEED_BALANCE == 1; then
	# We start from empty block groups and advance to more full ones.
	for usage in 0 10 20 40 60 80 96; do
		btrfs balance start -dusage=$usage /
	done
fi

kill $PID_KEEPALIVE

exit 0
